###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      build: phpdocker/mysql
      container_name: mysql
      working_dir: /var/www/html
      volumes:
      - ./data/mysql:/var/lib/mysql
      - ./phpdocker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=homestead
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      user: ${HOST_UID_GID}
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /var/www/html
      volumes:
          - ./:/var/www/html
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8001:80"

    php-fpm:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php-fpm
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
